// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace vms.entity.models
{
    public partial class Payroll
    {
        public Payroll()
        {
            PayrollDetails = new HashSet<PayrollDetail>();
        }

        public int PayrollId { get; set; }
        public int? BranchId { get; set; }
        public int? SettingsId { get; set; }
        public int? ExpenceId { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedTime { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Expence Expence { get; set; }
        public virtual Setting Settings { get; set; }
        public virtual ICollection<PayrollDetail> PayrollDetails { get; set; }
    }
}